travis:
  secure:
    BINSTAR_TOKEN: LAGDlWFCXlhR0KH8nadtp3qKN+FticXhFchC50zTBQ1jCHkqeuANvU6wlIQCvfsJ/Ywg4evsXjZ8ABaStkSpav5uVEjWUl/ZKXNiUIRY3BS1k2Y9AxtBoWA4aodVcDbhQb0oNPb/A6y6M0xKA741xrspIyxmrZObZZJXGQg3QE9nPT6eUkLSstE0RnRZWt/Q8CKJ8iEElATpw1XnztdVW0hlHu1Y8+VOyhy/Pe5D+ERwMPkVCCpGFPoHAJKUgi19nOcb1Qgd1G73SoUYg4VPFVugd9f1wbR2o6CNkG840Hlq3YfS7vTTF8ehmu/yq0GBbVpgb4FhMFY7AxDP7aGsnFvwjXwk2q3YPoA6JTCqtCEdSCgM9ur/XOL26wm2xQz9yTub9ikhELD+pxmGGUDHqE1Zx4R3/tVsPqpsD2wZU4Eu3d+cdWMXXBxtpQqLyNUjk5fdQA81743XmC3yqlKBFWzu7HQL1c47EvxqcgVHAVcVnd7/lEWlDxJj0JvoLWAzwv4iVeTkFsTx9RswSx/xSdgsapSpgxVO9GXsuILlmHguYgcyQajvYJYUtSYT18mZC8q9ANkEBXxnTVC/DshbIXSMUc8MJvmL4swnB4APQI51Ir3XSLxnY5H8PYy8Mp7yoN+5qTf/xSLwJRFoMSY/QrelwFti1wLpMOMsi5h1h6k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
