travis:
  secure:
    BINSTAR_TOKEN: kP89hcW8dPT4hAKB6A96PuSMcgpetBnkXLl3LYT/6ft6Pt+TnPFGHxkRZ5Yjf3GgVz9C6sn1QWwF6G+5+TkKfjnCm41vN2HAY2X0X7qNWwxZpLPXKmzLStm6GKb3f5qPCN3AsOWm63Z3/hXbroSQIzbEB0sXgpNv9lvIgsy2r2F7D95Vb0xBeU7DWoSM/7dRU0dG7pOXujF/NyO9V6UO9efw2WWk/dgkW0tLIvGVSeJecTvUJMb4w0S/NptD6xvu2cvZdpcn7iE87aM+3e0fT5NyanIeeJTPaqWzABSjf6bHz65LtrfEe+zJnrCLl654O2+KwKyR8GmrD1IbxdSJ0jEHygTgZv7sjx6msQBVcxc2wT9KKk8OccmfcbXUBKJzpEpU7JH+OhvbENtMrScdW1l2lxZ2P1dh1PVMX1gsgGeUwONS9Q+ADr9I6uyI3b4RcKNP7LIHp50jQr3rgaeEBKAlrYME7+7JkN7GTRRMi7mXE1x+WSIl/XlPpK3PfMI0lylV+8vFWn5bvDxcSqYh5x2wxEGhcQRO9x5b9TPZqApt9cntKFvv4Gob9ZwN7WsQgAvowTb83UOAu43meodLUm8CcJFaO291BOLUsQ83z/qbaWIqVJnocW+AUYBVKvfy/6FUMoDHrQzjMkhS1h8KL3rl2/Z8RSMU1LjVRg8wtDo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
