appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HTLmN/5KvYzQshGJLixc8VTT7TCeKjya+BR2+KFxoU3Mufx2Pp45RQAifQdu8hYkAJ5qigO4HY13E6u461S/F2cC2uH7UCi6WkgZmyY7rrxTGuPnj5m+Q4zbsVuHw1kBHmV4NTm7ASj0u/6/X3a0ADIPmp8oh2GF3DO70cT4aXf+TyKCpl/C5ld6ys3QHDJ028JqzdGYQi5dteXyL1b1D1SxyAUxYuy0oYd4pd6eovoCxwnSyIgRYgd/bqKX+enwXOhog/J/+ux8gK3Ha+xO+yUoeaYfiWreCOw+YfCD95JoPl7yIOZPnZM4cN/6WUEqcn3hGgk2oIAnlRJSOBdQMUrfhEgTvCZAeX1F2lJ21W2zZgiFMTqGMSWiXHEsQTilowXExeumFipUP6J3A/jdiypT8C0orrGSETMUbpvnryNzSpa2rP+86rPAH0qYVVfd3r/ReIpEj72bEYz+5S3bzOx3hSlL1OnsXaIL6Q/ZmJoiqOEZ78/bCQB3DbgZ6r0CJ2FHtv9/WB3OMKBW+IkRczwcZdGorj7UNWbB8e9h9KGsLvVXCriTOB55xp7dxltNh9DJrDNqaNuo4ZTOoWg+m63lsQuO14a/B/Bkhyzp3b6xBSVPouXQQLHsJWxYEHzLJ3oywg0tIVDjsp1b3tFKEYg/FWI+NNOHj7TpGR9S6eY=}
