travis:
  secure:
    BINSTAR_TOKEN: YAtUcug/xdZNAMPbXsDRUkVdvDd70ZrT8tlXhjZw9NGtD2y5hOMwRb/SiFA6R6lFDvuVvP1NycN/wO813GrUT9DgHfI9D0CUbBnWOe2FSTe0vdT3pWOvdbHAWTbkeGIV1SHgDQkD1npDm4QQQhBTr+EzOqPRDMe4aN8kUI6+kwACm716bDSiW1AmRVU6CIPMgGgcc+omgqqPp4Sfdb7NfuK165tnr5ploR59Qw7zhkDdNxb4xPvPiT8r/t6sxevVMyI80SI3qB/qrazACLj40QIfrRzyOdjaCc+W6xkozGa5+ksyxmwgD93lg/RDXrXiW0EFLxl7qUxyh6+cfpiOflvcWtm4hRqeIjDKHm+TmahQlZIod0egfobOIRedTSQlSx8v9wfyMf82QzWvmYn4MINxVgqGd+QhU8YSlFRwpQS6syYPup3CO/SblPLbrHf8pr0FiNm8SpcrfLvLE8Kk6tw5q4+hB9dphuGk52/kQnVvfjQlTjC8WSrJCqZPZ5mcd2kqSTej8nT+KMgRu1+VLoFUdP0u80sdOi7+WCKjidHxz0Tqu7+QHlVqBJGLzVQnlO5kguoVt1iHBAdY478VOhqL5/lTYG/x/r1eGiUB9CIxqAAIpfIecof+4qxoaO97tSHRUrpyzRFa6l36VtnIaZv/wCfuSiygry3NOwi42P0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
